;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-append
	evil-forward-char
	evil-mouse-drag-region
	evil-normal-state
	evil-previous-line
	evil-undo
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-force-normal-state
	evil-insert
	evil-next-line
	evil-record-macro
	evil-search-next
	org-self-insert-command
	save-buffers-kill-terminal
	))
