;;; my-fill.el --- This is my autofill plugin -*-lexical-binding:t; -*-
;;; Commentary:
;;; modify the input-config-alist can change the name and effect, the auto-fill is filling whenever you type (toggle with minor-mode), the my-fill one is just filling whit shorcuts.

(setq input-config-alist
      '(("beg" . (lambda ()
		    (interactive)
		    (let ((title (read-string "input your title:")))
		      (insert "\\begin{}\\end{}")
		      (backward-char 6)
		      (useful_begin title))))
	("bar" . (lambda ()
		    (insert "\\overline{}")
		    (backward-char 1)))
	("j" . (lambda ()
		  (insert "\n$$\n\n$$")
		  (backward-char 3)))
	("tikz" . (lambda ()
		     (insert "#+header: :header \'(\"\\usepackage{tikz-cd}\") \n#+beghin_latex\n\\begin{tikzcd}[color=white]\n\n\\end{tikzcd}\n#+end_latex")
		     (backward-char 25)))

	("\(" . (lambda ()
		  (insert "\\left(\\right")
		  (backward-char 6)))
	("\{" . (lambda ()
		  (insert "\\{\\")
		  (backward-char 1)))
	("|" . (lambda ()
		  (insert "|  |")
		  (backward-char 2)))
	("||" . (lambda ()
		  (insert "\\lVert  \\rVert")
		  (backward-char 7)))
	("sq". (lambda ()
		  (insert "\\sqrt{}")
		  (backward-char 1)))
	("sum" . (lambda ()
		  (insert "\\sum\\limits_{}")
		  (backward-char 1)))
	("lim" . (lambda ()
		    (insert "\\lim\\limits_{}")
		    (backward-char 1)))
	("an" . (lambda ()
		      (insert "\\langle  \\rangle")
		      (backward-char 8)))
	("f" . (lambda ()
		   (insert "\\frac{}{}")
		   (backward-char 3)))
	("cal" . (lambda ()
		    (insert "\\mathcal{}")
		    (backward-char 1)))
	("err" . (lambda ()
		   (insert "if err!=nil{\n\n}")
		   (backward-char 2)))
	))

(defun useful_begin (title)
  "Insert begin braket with TITLE."
  (save-excursion
    (backward-char 1)
    (insert title)
    (forward-char 6)
    (insert title)))

(defun take_fragment (n)
  "Taking the fragment of string of length N."
  (let* (
	 (end-pos (point))
	 (start-pos (max 0 (- (+ 1 (point)) n))))
    (buffer-substring start-pos end-pos)))

(defun my-fill-function ()
  "Auto change the content to tex command."
	(interactive)
	(let ((mark t))
	(dotimes (i 3)
	(let* ((txt (take_fragment (- 4 i)))
		(res (assoc txt input-config-alist)))
	(when (and res mark)
		(setq mark nil)
		(backward-char)
		(let ((result (cdr res)))
			(forward-char 1)
			(delete-char (- (length txt)))
			(funcall result))))
	)))

(setq auto-input-alist
      '(("jf" . (lambda ()
		  (insert "_{}")
		  (backward-char 1)))
	("_" . (lambda ()
		  (insert "_{}")
		  (backward-char 1)))
	("jk" . (lambda ()
		   (insert "^{}")
		   (backward-char 1)))
	("jj" . (lambda ()
		  (insert "$$")
		  (backward-char 1)))
	("bm" . (lambda ()
		   (insert "\\boldsymbol{}")
 	           (backward-char 1)))
	("bb" . (lambda ()
		   (insert "\\mathbb{}")
		   (backward-char 1)))
	("fk" . (lambda ()
		   (insert "\\mathfrak{}")
		   (backward-char 1)))
	("->" . (lambda () (insert "\\rightarrow ")))
	("-<" . (lambda () (insert "\\leftarrow ")))
	("xx" . (lambda () (insert "\\times ")))
        (";b" . (lambda () (insert "\\beta")))
	(";a" . (lambda () (insert "\\alpha")))
        (";t" . (lambda () (insert "\\theta")))
	(";k" . (lambda () (insert "\\kappa")))
	(";l" . (lambda () (insert "\\lambda")))
	(";o" . (lambda () (insert "\\omega")))
	(";g" . (lambda () (insert "\\gamma")))
	(";e" . (lambda () (insert "\\epsilon")))
	(";s" . (lambda () (insert "\\sigma")))
	(";d" . (lambda () (insert "\\delta")))
        (";B" . (lambda () (insert "\\Beta")))
	(";A" . (lambda () (insert "\\Alpha")))
        (";T" . (lambda () (insert "\\Theta")))
	(";K" . (lambda () (insert "\\Kappa")))
	(";L" . (lambda () (insert "\\Lambda")))
	(";O" . (lambda () (insert "\\Omega")))
	(";G" . (lambda () (insert "\\Gamma")))
	(";E" . (lambda () (insert "\\Epsilon")))
	(";S" . (lambda () (insert "\\Sigma")))
	(";D" . (lambda () (insert "\\Delta")))
	(">=" . (lambda () (insert "\\geq ")))
	("<=" . (lambda () (insert "\\leq ")))
	("-|" . (lambda () (insert "\\perp ")))
	("+-" . (lambda () (insert "\\pm ")))
	("!=" . (lambda () (insert "\\neq ")))
	("!>" . (lambda () (insert "\\mapsto")))
	("..." . (lambda () (insert "\\cdots ")))
	("===" . (lambda () (insert "\\equiv ")))
	("ptl" . (lambda () (insert "\\partial ")))
	("-->" . (lambda () (insert "\\longrightarrow ")))
	("--<" . (lambda () (insert "\\longleftarrow ")))
	))

(defun my-auto-fill ()
	(let ((mark t))
	(dotimes (i 3)
	(let* ((txt (take_fragment (- 4 i)))
		(res (assoc txt auto-input-alist)))
	(when (and res mark)
		(setq mark nil)
		(backward-char)
		(let ((result (cdr res)))
			(forward-char 1)
			(delete-char (- (length txt)))
			(funcall result))))
	)))

(define-minor-mode my-latex-math-auto-fill-mode
  "Auto filling for LaTeX math."
  :lighter " math-fill"
  (if my-latex-math-auto-fill-mode
      (add-hook 'post-self-insert-hook
                #'my-auto-fill
                nil t)   ; LOCAL
    (remove-hook 'post-self-insert-hook
                 #'my-auto-fill
                 t)))

;;; my-fill.el ends here
