;; This is my autofill plugin, modify the input-config-alist can change the name and effect, and the default shortcut to avoke it is C-f
(setq input-config-alist
      '(("beg" . ((lambda ()
		    (interactive)
		    (let ((title (read-string "input your title:")))
		      (insert "\\begin{}\\end{}")
		      (backward-char 6)
		      (useful_begin title)))))
	("k" . ((lambda ()
		  (insert "^{}")
		  (backward-char 1))))
	("a" . ((lambda ()
		  (insert "\\alpha")
		  )))
        ("b" . ((lambda ()
		  (insert "\\beta")
		  )))
        ("t" . ((lambda ()
		  (insert "\\theta")
		  )))
	("bar" . ((lambda ()
		    (insert "\\overline{}")
		    (backward-char 1))))
	("j" . ((lambda ()
		  (insert "$$\n\n$$")
		  (backward-char 3))))
	("tikz" . ((lambda ()
		     (insert "#+header: :header \'(\"\\usepackage{tikz-cd}\") \n#+begin_latex\n\\begin{tikzcd}[color=white]\n\n\\end{tikzcd}\n#+end_latex")
		     (backward-char 25))))
	("f" . ((lambda ()
		   (insert "\\frac{}{}")
		   (backward-char 3))))
	("p" . ((lambda ()
		     (insert "\\partial"))))
	("\(" . ((lambda ()
		   (insert "\\left(\\right")
		   (backward-char 7))))
	("s". ((lambda ()
		  (insert "\\sqrt{}")
		  (backward-char 1))))
	))

(defun useful_begin (title)
  ;(interactive "sinput your title:")
  (save-excursion
    (backward-char 1)
    (insert title)
    (forward-char 6)
    (insert title)))

(defun test (n)
  (let* (
	 (end-pos (+ 1 (point)))
	 (start-pos (max 0 (- end-pos n))))
    (buffer-substring start-pos end-pos)))

(defun myfill ()
  "Auto change the content to tex command"
	(interactive)
	(backward-char)
	(let ((mark t))
	(dotimes (i 5)
	;;(message "%d" i)
	(let* ((txt (test (+ i 1)))
		(res (assoc txt input-config-alist)))
		;;(message txt)
	(when (and res mark)
		(setq mark nil)
		(let ((result (cdr res)))
			(forward-char 1)
			(delete-char (- (length txt)))
			(dolist (command result)
			(funcall command))))))))

;(evil-leader/set-key "k" 'myfill)
(global-set-key (kbd "C-f") nil)
(global-set-key (kbd "C-f") 'myfill)
