;; This is my autofill plugin, modify the input-config-alist can change the name and effect, and the default shortcut to avoke it is C-f
(setq input-config-alist
      '(("beg" . ((lambda ()
		    (interactive)
		    (let ((title (read-string "input your title:")))
		      (insert "\\begin{}\\end{}")
		      (backward-char 6)
		      (useful_begin title)))))
	("lim" . ((lambda ()
		    (insert "\\lim\\limits_{}")
		    (backward-char 1))))
	("k" . ((lambda ()
		  (insert "^{}")
		  (backward-char 1))))
	("a" . ((lambda ()
		  (insert "\\alpha")
		  )))
        ("b" . ((lambda ()
		  (insert "\\beta")
		  )))
        ("t" . ((lambda ()
		  (insert "\\theta")
		  )))
	("v" . ((lambda ()
		  (insert "\\bm{}")
		  (backward-char 1))))
	("ka" . ((lambda ()
		   (insert "\\kappa"))))
	("bar" . ((lambda ()
		    (insert "\\overline{}")
		    (backward-char 1))))
	("bm" . ((lambda ()
		   (insert "\\boldsymbol{}")
		   (backward-char 1))))
	("=" . ((lambda ()
		  (insert "\\equiv"))))
	("!" . ((lambda ()
		  (insert "\\not"))))
	("x" . ((lambda ()
		  (insert "\\times "))))
	("j" . ((lambda ()
		  (insert "$$\n\n$$")
		  (backward-char 3))))
	("tikz" . ((lambda ()
		     (insert "#+header: :header \'(\"\\usepackage{tikz-cd}\") \n#+begin_latex\n\\begin{tikzcd}[color=white]\n\n\\end{tikzcd}\n#+end_latex")
		     (backward-char 25))))
	("f" . ((lambda ()
		   (insert "\\frac{}{}")
		   (backward-char 3))))
	("par" . ((lambda ()
		     (insert "\\partial "))))
	("\(" . ((lambda ()
		   (insert "\\left(\\right")
		   (backward-char 6))))
	("\{" . ((lambda ()
		   (insert "\\{\\")
		   (backward-char 1))))
	("|" . ((lambda ()
		  (insert "|  |")
		  (backward-char 2))))
	("||" . ((lambda ()
		 (insert "\\lVert  \\rVert")
		 (backward-char 7))))
	("sq". ((lambda ()
		  (insert "\\sqrt{}")
		  (backward-char 1))))
	("su" . ((lambda ()
		  (insert "\\sum\\limits_{}")
		  (backward-char 1))))
	("p" . ((lambda ()
		  (insert "\\prod\\limits_{}")
		  (backward-char 1))))
	("l". ((lambda ()
		 (insert "\\lambda"))))
	("o". ((lambda ()
		 (insert "\\omega"))))
	("g". ((lambda ()
		 (insert "\\gamma"))))
	("e". ((lambda ()
		 (insert "\\epsilon"))))
	("s". ((lambda ()
		 (insert "\\sigma"))))
	("angle" . ((lambda ()
		      (insert "\\langle  \\rangle")
		      (backward-char 8))))
	("bb" . ((lambda ()
		   (insert "\\mathbb{}")
		   (backward-char 1))))
	("cal" . ((lambda ()
		    (insert "\\mathcal{}")
		    (backward-char 1))))
	("->" . ((lambda ()
		   (insert "\\rightarrow "))))
	("-->" . ((lambda ()
		    (insert "\\longrightarrow "))))
	("-<" . ((lambda ()
		   (insert "\\leftarrow "))))
	("--<" . ((lambda ()
		    (insert "\\longleftarrow "))))
	("err" . ((lambda ()
		    (insert "if err!=nil{\n return err\n}"))))
	))

(defun useful_begin (title)
  "Insert begin braket with TITLE."
  (save-excursion
    (backward-char 1)
    (insert title)
    (forward-char 6)
    (insert title)))

(defun take_fragment (n)
  "Taking the fragment of string of length N."
  (let* (
	 (end-pos (point))
	 (start-pos (max 0 (- (+ 1 (point)) n))))
    (buffer-substring start-pos end-pos)))

(defun myfill ()
  "Auto change the content to tex command."
	(interactive)
	(let ((mark t))
	(dotimes (i 5)
	(let* ((txt (take_fragment (- 6 i)))
		(res (assoc txt input-config-alist)))
	(when (and res mark)
		(setq mark nil)
		(backward-char)
		(let ((result (cdr res)))
			(forward-char 1)
			(delete-char (- (length txt)))
			(dolist (command result)
			  (funcall command)))))
	)))

(provide 'myfill)
;;;myfill.el ends here
